import type { FAQEntry } from '@/sections/home/FAQ/faqData';
import type { Testimonial } from '@/sections/home/Testimonials/testimonialData';

export const digitalMarketingTestimonials: Testimonial[] = [
  { id: 'marketing-visibility', name: 'Brian K.', meta: 'Business Owner', initials: 'BK', avatarTone: 'orange', rating: 5, title: 'Clear support for improving our visibility.', excerpt: 'Laybrotech helped us understand where our online presence needed work and gave us a more focused marketing direction.', fullReview: 'Laybrotech helped us understand where our online presence needed work and gave us a more focused marketing direction. The communication was clear and the recommendations were practical for our business.' },
  { id: 'marketing-campaigns', name: 'Martha N.', meta: 'Operations Lead', initials: 'MN', avatarTone: 'charcoal', rating: 5, title: 'Campaign planning felt organised.', excerpt: 'The team helped us plan campaigns around our audience instead of posting randomly and hoping something worked.', fullReview: 'The team helped us plan campaigns around our audience instead of posting randomly and hoping something worked. It made our marketing feel more structured and easier to review.' },
  { id: 'marketing-strategy', name: 'Samuel O.', meta: 'Director', initials: 'SO', avatarTone: 'green', rating: 5, title: 'They connected the website and marketing work.', excerpt: 'The advice covered both our website and the campaigns sending people there, which helped us see the bigger picture.', fullReview: 'The advice covered both our website and the campaigns sending people there, which helped us see the bigger picture. Laybrotech focused on practical improvements we could make over time.' },
  { id: 'marketing-communication', name: 'Aisha T.', meta: 'Administrator', initials: 'AT', avatarTone: 'warm', rating: 5, title: 'Reliable communication throughout.', excerpt: 'We always understood what was being worked on and why it mattered for our campaign goals.', fullReview: 'We always understood what was being worked on and why it mattered for our campaign goals. The process was professional and easy to follow.' },
  { id: 'marketing-traffic', name: 'Grace L.', meta: 'Service Provider', initials: 'GL', avatarTone: 'orange', rating: 5, title: 'Better direction for website traffic.', excerpt: 'Laybrotech helped us think about the kind of visitors we wanted and how to make our website clearer for them.', fullReview: 'Laybrotech helped us think about the kind of visitors we wanted and how to make our website clearer for them. The work gave us a stronger foundation for future marketing.' },
  { id: 'marketing-leads', name: 'Peter M.', meta: 'Manager', initials: 'PM', avatarTone: 'charcoal', rating: 5, title: 'Focused on real enquiries, not vanity metrics.', excerpt: 'The conversations were about useful actions customers should take, not just likes or impressions.', fullReview: 'The conversations were about useful actions customers should take, not just likes or impressions. That made the marketing support feel tied to real business goals.' },
];

export const digitalMarketingFaqItems: FAQEntry[] = [
  { id: 'what-is-digital-marketing', question: 'What is digital marketing?', answer: 'Digital marketing is the use of online channels such as search engines, websites, social media, content, email, and paid advertising to reach and engage customers.' },
  { id: 'seo-timeline', question: 'How long does SEO take?', answer: 'SEO is an ongoing process. The time needed to see meaningful improvement depends on competition, website quality, content, technical factors, and the current search position.' },
  { id: 'meta-ads', question: 'Do you manage Facebook and Instagram ads?', answer: 'Yes. Laybrotech can plan, launch, monitor, and optimise Facebook and Instagram advertising campaigns based on agreed objectives.' },
  { id: 'small-business', question: 'Can digital marketing help a small business?', answer: 'Yes. A focused digital strategy can help small businesses improve visibility, communicate their value, and reach customers online.' },
  { id: 'google-ads', question: 'Do you manage Google Ads?', answer: 'Yes. Google Ads campaigns can be built around search keywords, audiences, conversion goals, and available campaign budgets.' },
  { id: 'reports', question: 'Do you provide monthly reports?', answer: 'Where ongoing marketing management is provided, campaign performance can be reviewed and reported regularly based on the agreed service.' },
  { id: 'website-improvements', question: 'Can you help improve an existing website for marketing?', answer: 'Yes. Website structure, SEO, landing pages, analytics, and conversion-focused elements can be reviewed and improved where appropriate.' },
];
